### add
POST localhost:9999/cinemas
Content-Type: application/json

{
  "name" : "Grande cinema ruse",
  "cityId" : 8,
  "phoneNumber" : "0899878787",
  "address" : "okolovrysten pyt 77",
  "email" : "cinemaring@abv.bg"

}

### edit
PUT localhost:9999/cinemas
Content-Type: application/json

{
  "id" : 27,
  "name" : "New Cinema ",
  "cityId" : 10,
  "phoneNumber" : "0999888888",
  "address" : "okolovrysten pyt 77",
  "email" : "cinemaring@abv.bg"

}

### remove
DELETE localhost:9999/cinemas/10

### get by id
GET localhost:9999/cinemas/11


### get all by city name
GET localhost:9999/cinemas
Content-Type: application/json

{
  "name" : "burgas"
}