### add
POST localhost:9999/cinemas
Content-Type: application/json

{
  "name" : "Furious cinema",
  "cityId" : 6,
  "phoneNumber" : "0899878787",
  "address" : "okolovrysten pyt 77",
  "email" : "cinemaring@abv.bg"

}

### edit
PUT localhost:9999/cinemas
Content-Type: application/json

{
  "id" : 27,
  "name" : "New Cinema Arena",
  "cityId" : 10,
  "phoneNumber" : "0999888888",
  "address" : "okolovrysten pyt 77",
  "email" : "cinemaring@abv.bg"

}

### remove
DELETE localhost:9999/cinemas/10

### get by id
GET localhost:9999/cinemas/11


### get all cinemas with optional filter by city name or ptojection type
GET localhost:9999/cinemas
Content-Type: application/json

{
  "city" : "burgas",
  "type" : "3D Real"
}
