### add
POST localhost:9999/cities
Content-Type: application/json

{
  "name" : "plovdiv"
}

### edit
PUT localhost:9999/cities
Content-Type: application/json

{
  "id" : 10,
  "name" : "burgas"

}

### remove
DELETE localhost:9999/cities/4

### get by id
GET localhost:9999/cities/8

### get all
GET localhost:9999/cities