### add
POST localhost:9999/halls
Content-Type: application/json

{
  "name" : "zala DELUXE",
  "rowsNumber" : 4,
  "seatsPerRow" : 10,
  "cinemaId" : 34
}

### edit
PUT localhost:9999/halls
Content-Type: application/json

{
  "id" : 17,
  "name" : "zala DELUXE",
  "rowsNumber" : 3,
  "seatsPerRow" : 10,
  "cinemaId" : 34
}

### remove
DELETE localhost:9999/halls/12

### get by id
GET localhost:9999/halls/10

