### add
POST localhost:9999/halls
Content-Type: application/json

{
  "name" : "zala VIP2",
  "capacity" : 40,
  "cinemaId" : 26
}

### edit
PUT localhost:9999/halls
Content-Type: application/json

{
  "id" : 11,
  "name" : "Zala 3",
  "capacity" : 40,
  "cinemaId" : 11
}

### remove
DELETE localhost:9999/halls/12

### get by id
GET localhost:9999/halls/10

