### add
POST localhost:9999/movies
Content-Type: application/json

{
  "title" : "title32",
  "duration" : 120,
  "description" : "descrjjiption",
  "actors" : "Georg Georg",
  "premiere" : "2022-03-18",
  "director" : "director",
  "categoryId" : 1,
  "poster_url" : "kjbhkjhnkj"

}


### delete
DELETE localhost:9999/movies/5

### edit
PUT localhost:9999/movies
Content-Type: application/json

{
  "title" : "title",
  "duration" : 125
}


### get by id
GET localhost:9999/movies/6