### add
POST localhost:9999/projections
Content-Type: application/json

{
  "movieId" : 3,
  "hallId" : 11,
  "typeId" : 4,
  "startTime" : "2022-03-11"

}


### edit
PUT localhost:9999/projections
Content-Type: application/json

{
  "id" : 3,
  "movieId" : 2,
  "hallId" : 9,
  "typeId" : 4,
  "startTime" : "2022-03-11"
}

### remove
DELETE localhost:9999/projections/5


### get by id
GET localhost:9999/projections/1